### ISSUE TITLE
Unable to attach screenshots for failed test cases in Cypress Cucumber Report

### ISSUE THREAD

**Issue by Gauri94** [dane-harnett/cypress-cucumber-attach-screenshots-to-failed-steps#1]
Unable to attach screenshots for failed test cases in Cypress Cucumber Report
Below are the required files that are changed:

**Package.json:**

{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cypress:open": "cypress open",
    "cy:report": "node ./cypress/report.js"
  },
  "author": "saurabh",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^6.9.1",
    "cypress-cucumber-attach-screenshots-to-failed-steps": "^1.0.0",
    "cypress-cucumber-preprocessor": "^4.2.0",
    "multiple-cucumber-html-reporter": "^1.18.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true
    }
  },
  "dependencies": {
    "yargs": "^16.2.0"
  }
}

*************************************************************************************

**index.js in support folder:**
// This example support/index.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************
//Add Screenshot to Cucumber Report 
import "cypress-cucumber-attach-screenshots-to-failed-steps"

// Import commands.js using ES2015 syntax:
import './commands'

******************************************************************************************
**report.js:**

///<reference types='cypress'/>
const report = require("multiple-cucumber-html-reporter");
report.generate({
jsonDir: "./cypress/cucumber-json/",  // ** Path of .json file **//
reportPath: "./cypress/cucumber-report/",
});

**************************************************************************************************
Repro steps:
1. Installed node module: npm install --save-dev cypress-cucumber-attach-screenshots-to-failed-steps
2. Imported package in support index.js: import "cypress-cucumber-attach-screenshots-to-failed-steps"

**Comment by dane-harnett** [comment]
This all looks correct, can you advise what commands you are running to execute the tests and then generate the report?

**Comment by Gauri94** [comment]
Hi Dane,

Thank you for your response.
I'm able to resolve this issue by reinstalling the node modules.

However, could you please suggest how to add metadata like browser name and
browser version in cucumber reports?

Thanks & Regards,
Gouri Soneja

**Comment by dane-harnett** [comment]
Hi Gouri,

I'm glad to hear you have solved your issue :)

I will plan to include a video showing how to set those details in cucumber reports on my YouTube channel over at https://www.youtube.com/DaneHarnett

**Comment by Gauri94** [comment]
Thank you.
Eagerly waiting for it. 😊😊
