### ISSUE TITLE
Broken Image on screenshot

### ISSUE THREAD

**Issue by iepoch** [dane-harnett/cypress-cucumber-attach-screenshots-to-failed-steps#2]
Hey Dane
Currently, I am running the following:

```  
    "cypress": "^8.2.0",
    "cypress-cucumber-attach-screenshots-to-failed-steps": "^1.0.0",
    "cypress-cucumber-preprocessor": "^4.2.0",
    "cypress-xpath": "^1.6.2",
    "multiple-cucumber-html-reporter": "^1.18.0"
   ```

I have a `.cypress-cucumber-preprocessorrc.json` file so I would not have a lot of data in the package.json file and that setup looks like the following
```
{
    "cucumberJson":{
        "generate": true,
        "outputFolder":"cypress/cucumber-json",
        "filePrefix":"",
        "fileSuffix": ".cucumber"
    },
    "nonGlobalStepDefinitions": true
}
```

Everything works and I created a failure in the test not in the Site itself as I am just using www.google.com to do a random search. When the failure generates it does create a snapshot. I was able to view this from the `cypress/snapshot` folder. 
But the report does not link to this image. The image gets returned as `<img class="screenshot" src="data:image/png;base64,undefined">`
There could be an update with cypress that now changes where you mapping it from as it's getting undefined. Just an idea.

**Comment by dane-harnett** [comment]
Hey,
We are grabbing the path to the screenshots folder via the cypress config...
https://github.com/dane-harnett/cypress-cucumber-attach-screenshots-to-failed-steps/blob/main/index.js#L2
By default this is `cypress/screenshots` however you're mentioning `cypress/snapshots` I wonder if something has changed.
Are you able to inspect what the value of `Cypress.config('screenshotsFolder');` is returning?

**Comment by dane-harnett** [comment]
When I have a moment I will also check to see if Cypress v8.x has broken this as I have only tested on v7.x

**Comment by iepoch** [comment]
> Hey,
> We are grabbing the path to the screenshots folder via the cypress config...
> https://github.com/dane-harnett/cypress-cucumber-attach-screenshots-to-failed-steps/blob/main/index.js#L2
> By default this is `cypress/screenshots` however you're mentioning `cypress/snapshots` I wonder if something has changed.
> Are you able to inspect what the value of `Cypress.config('screenshotsFolder');` is returning?
Sorry haven't responded been heavy work load but I can check noticed that it was getting a Undefined from the Image path I suspect it's doing the same. So far checking the configuration this is what it is returnting `screenshotsFolder:"cypress/screenshots" `

**Comment by iepoch** [comment]
Also you are right I miss typed and said `snapshots` when really it is the folder for `screenshots` however it still doesn't pickup that there is a screenshot in this folder location. I also noticed that when I want to add it to the config file I do have to put `./cypress/screenshots`  but the default is `cypress/screenshots`

**Comment by dane-harnett** [comment]
@iepoch Thanks for the replies, I will try test against Cypress v8 when I have a moment, that's the current lead I have.

**Comment by dane-harnett** [comment]
@iepoch I have attempted to replicate your setup in my project and everything is working as expected. So it's not Cypress v8 as I guessed.

Could you please let me know the path of the screenshot files that are generated? Could you give me a full example?

I'm wondering if the image is within a subfolder, which I don't think I have accounted for.

**Comment by iepoch** [comment]
Yea I tried changing the config on Cypress to `./cypress/screenshots` to see if that was the issue. But it wasn't so I am not certain what I am missing. I have done any other setups other than leaving it to default. but not sure what could be causing the issue. I thought maybe it was a subfolder issue as well. Here is a view of my entire folder structure. Also, I am on windows instead of Mac. 
![image](https://user-images.githubusercontent.com/7504929/129464937-ecdb4009-7cf7-46d2-93cd-c993c9e2c5d6.png)
And here is my cypress.json
```{
  "env": {
    "TAGS": "not @ignore or @focus"
  },
  "ignoreTestFiles": "*.js",
  "testFiles": "**/*.{feature, features}",
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "video": false,
  "chromeWebSecurity": false,
  "firefoxWebSecurity": false,
  "trashAssetsBeforeRuns": true,
  "defaultCommandTimeout": 60000,
  "pageLoadTimeout": 80000
}
```
Let me know if you have any ideas on this. Would be great to thank you for writing this.

**Comment by iepoch** [comment]
Hey Dane, 
I think it was something in the node_modules. I did a bit of removing them and reinstalling the packages. I am not sure what happened but it was the last thing I decided to try and it's working now. Not sure why it happened but it seems to be pulling it from the folder now. Sorry to have been a bother on it. Thanks again.

**Comment by dane-harnett** [comment]
hey @iepoch good to hear you solved it, I will be sure to suggest deleting node_modules and re-installing as a troubleshooting step next time :)

**Comment by Niemetz** [comment]
Hi iepoch
  I experienced the same issue that you had...
  I updated cypress to v9.4.1 but it did not resolve the issue... I was wondering what node_modules you deleted before you install a new version of cypress?
  Thank
  J.N

**Comment by Niemetz** [comment]
![Screen Shot 2022-02-08 at 3 03 43 PM](https://user-images.githubusercontent.com/20528680/153066738-3bef0c3b-f44e-4bab-ae3b-df3cda1cbf5f.png)

**Comment by Niemetz** [comment]
My project folder structure
![Screen Shot 2022-02-08 at 3 05 52 PM](https://user-images.githubusercontent.com/20528680/153067008-1ced1a85-2a1d-462c-9701-5903e055771f.png)
:

**Comment by Niemetz** [comment]
Any tips for me?  Thanks.  J.N

**Comment by Niemetz** [comment]
Hi Dane!
  I'm new to Javascript/TypeScript... but I'd like to debug the code... where can I write the log message along the code so I can what goes wrong?
  I knew that after each scenario, if there is an error, then your code will take the error screenshot and attach it to the step, but what I don't know is:  if I insert some kind of message like console.lg() (or anything like that), then where I can view my log message?
  Thanks
  John Nguyen

**Comment by Niemetz** [comment]
From the Dev Tools I found an error and it looks like the code picked up a wrong file
![Screen Shot 2022-02-09 at 4 25 41 PM](https://user-images.githubusercontent.com/20528680/153292829-7e8c36a5-6e79-4360-89f6-5ad7d2e3074d.png)
.

**Comment by Niemetz** [comment]
Therefore the browser complaints that it was not able to find the file
![Screen Shot 2022-02-09 at 4 27 48 PM](https://user-images.githubusercontent.com/20528680/153292989-3dcc94ab-6649-42df-bdee-11d9c8266734.png)
:

**Comment by Niemetz** [comment]
![Screen Shot 2022-02-09 at 4 30 30 PM](https://user-images.githubusercontent.com/20528680/153293434-21dc0906-27f4-40c2-9db3-01dfea6bd819.png)

**Comment by dane-harnett** [comment]
OK cool, let's continue the discussion over on #5 so that the original poster doesn't continue to be notified.

**Comment by Niemetz** [comment]
Thanks Dane!  Will do!
