### ISSUE TITLE
Screenshots not attaching

### ISSUE THREAD

**Issue by dane-harnett** [dane-harnett/cypress-cucumber-attach-screenshots-to-failed-steps#5]
@niemetz raised that screenshots are not appearing in the report

**Comment by dane-harnett** [comment]
@niemetz can you try deleting the whole `node_modules` directory and running `npm install` - I believe this is caused from a corruption in the modules somehow.

Your other question about logs, they will probably appear in the terminal window that you run `npm run cy:run` or however you're running your tests.

**Comment by dane-harnett** [comment]
Let me know once you've tried deleting the whole node_modules and try again.

**Comment by Niemetz** [comment]
Will do.  Thanks Dane!

**Comment by Niemetz** [comment]
Hi Dane.  the issue still exists after I removed and re-install ...
There some installation warning.. not sure they are related to cucumber?
![Screen Shot 2022-02-09 at 4 41 05 PM](https://user-images.githubusercontent.com/20528680/153296042-456d8016-3221-4d78-8676-125e0441bd44.png)

**Comment by Niemetz** [comment]
If you have time, would you please help take a look at my simple project and see if I have done it  right?  
Thanks Dane!
PS:  Everything works well.... I just can't attach the screenshot to the erred step in the html report.

https://github.com/Niemetz/cypress-automation

**Comment by Niemetz** [comment]
I really appreciate your help Dane.  I'm new to JS and TS and have little clue how they work :-).

**Comment by Niemetz** [comment]
I also did that too... actually, I cleaned up all files that were produced by Cypress and re-ran the test, but the issue still persists.
  Thanks for the tip Dane!

**Comment by Niemetz** [comment]
Based on the execution message that your code produces, I can confirm that the path and filename of the screenshot is correct:
![Screen Shot 2022-02-09 at 5 44 25 PM](https://user-images.githubusercontent.com/20528680/153303217-25681ce7-e0ca-4866-82cd-492768152353.png)

**Comment by dane-harnett** [comment]
I can try out with your repo on the weekend. In the mean time can you let me know any other details about your system like operating system and version, nodejs version and anything else relevant maybe browser version

**Comment by Niemetz** [comment]
Good morning Dane!
  I have updated my repo. 
  Have a great weekend!
 Thanks
 J.N

**Comment by dane-harnett** [comment]
Hi @Niemetz I took a look and seems the `pageobjects` folder is missing from the repository?

**Comment by Niemetz** [comment]
Good morning Dane!
  Thank you for spending your weekend time on helping to resolve this issue.
  The way I implemented the pageobjects  is different from the common practice where most people would do is implement the field retrieval methods right on a page.  I, on the other hand, do not implement the element-retrial methods on the page, but rather from the user class (StepDefinitionImplementation ) where I made all of the methods re-useable across all pages.  You can find the pageobjects under folder "**cypress/integration/pageobjects/<all the page objects>**.  Sorry for the confusion it might cause.... It is just a different implementation of pageobjects.
  To execute the whole program, you can issue this command: > **npm run all**
  Thanks Dane!

**Comment by Yohandah** [comment]
I had a similar issue and this is because the cucumber-report-html folder existed, I deleted the folder and the screenshots are attaching.

**Comment by Niemetz** [comment]
@Yohandah 
  Thanks for the tip... but I'm still not sure how does it work... if I don't specify the folder for html,, then how how cypress knows where to put the html test run results?
  If I understand you correctly, I need to delete the folder for the html test run result?  Please help elaborate on the steps.
  Thanks...
   PS: I'll try this when I got home and see how it works...

**Comment by beohoang98** [comment]
After upgrade Cypress v10, the screenshot cannot found anymore. I think the problem is Cypress change the way they store the screenshots

https://docs.cypress.io/guides/references/migration-guide#Generated-Files 

Example: `cypress/screenshots/some/more/sub/folder/step_name (failed).png`

So is the path `${screenshotsFolder}/${Cypress.spec.name}/${screenshotFileName}` here work anymore?

**Comment by Niemetz** [comment]
> After upgrade Cypress v10, the screenshot cannot found anymore. I think the problem is Cypress change the way they store the screenshots
> 
> https://docs.cypress.io/guides/references/migration-guide#Generated-Files
> 
> Example: `cypress/screenshots/some/more/sub/folder/step_name (failed).png`
> 
> So is the path `${screenshotsFolder}/${Cypress.spec.name}/${screenshotFileName}` here work anymore?

Hoang!
  I think Cypress is dead.  It is way too fragile to use.  It requires quite a lot of dependencies/plug-ins.
  I moved to Playwright and never look back again. It is a much better tools for Test Automation... even much better than Selenium WebDriver.
  Take a look at Playwright and you will love it.
  John Nguyen

**Comment by beohoang98** [comment]
I won't think Cypress is bad. It's still good with active development

By the way, I see with the new version of [@badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor), the screenshot attachment/embed in json/report information is **already supported**.

**Comment by dane-harnett** [comment]
Yes @beohoang98 my recommendation going forward is to update to @badeball/cypress-cucumber-preprocessor and use the built in screenshot support.
